stages:
  - test
  - sync

deploy_to_github:
  stage: sync
  script:
    - git remote add github "https://$GITHUB_TOKEN@github.com/Team-1710-Informatics/Vercel-Scouting-App.git"
    - git push github $CI_COMMIT_SHA:refs/heads/main
  only:
    - main  # or whichever branch you want to trigger the pipeline for

#This is only for CI/CD piepline between gitlab and github repository. Delete to delete connection

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
sonarcloud-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [ "" ]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
    - develop

