stages:
  - sync

deploy_to_github:
  stage: sync
  script:
    - git remote add github https://github.com/Team-1710-Informatics/Vercel-Scouting-App.git
    - git push github

#This is only for CI/CD piepline between gitlab and github repository. Delete to delete connection